package vhms.login;


import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

public class ManagerLogin extends javax.swing.JFrame {

    Connection con;
    ResultSet rs;
    PreparedStatement pst;

    /**
     * Creates new form LoginFrame
     */
    public ManagerLogin() {
        initComponents();
        //txtEmail.setBackground(new Color(0,0,0,0));
       // txtPass.setBackground(new Color(0,0,0,0));
    }

    public void login() {
        String email = txtEmail.getText();
        char[] p = txtPass.getPassword();
        String pass = String.valueOf(p);
        int count = 0;
        String query = "select Email,Password from manager where Email = ? and Password = ?";
        if (!email.isEmpty()) {
            if (!pass.isEmpty()) {
                try {
                    con = DriverManager.getConnection("jdbc:mysql://localhost:3306/lunch_box", "root", "123");
                    pst = con.prepareStatement(query);
                    //set the parameter
                    pst.setString(1, email);
                    pst.setString(2, pass);
                    rs = pst.executeQuery();

                    while (rs.next()) {
                        count = rs.getRow();
                    }
                    if (count > 0) {
                        this.dispose();
//                        Managergranted mg= new Managergranted();
//                        mg.setVisible(true);
                        ManagerDashboard md = new ManagerDashboard();
                        // ls.lblWelcome.setText("Welcome " + name);
                        md.setVisible(true);
                } else {
                        JOptionPane.showMessageDialog(this, "You are not registered yet. \n Get registerd now", "Alert!", JOptionPane.ERROR_MESSAGE);
//                        this.dispose();
//                        ManagerReg mr = new ManagerReg();
//                        mr.setVisible(true);
                    }

                } catch (Exception e) {
                    e.printStackTrace();
                } finally {
                    try {
                        if (rs != null) {
                            rs.close();
                        }
                        if (pst != null) {
                            pst.close();
                        }
                        if (con != null) {
                            con.close();
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Please Enter Password", "Information", JOptionPane.INFORMATION_MESSAGE);
                txtPass.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Please Enter Email", "Information", JOptionPane.INFORMATION_MESSAGE);
            txtEmail.requestFocus();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(250, 100));
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(null);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel3.add(txtEmail);
        txtEmail.setBounds(110, 220, 230, 30);

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        jPanel3.add(txtPass);
        txtPass.setBounds(110, 270, 230, 30);

        btnLogin.setBackground(new java.awt.Color(255, 0, 0));
        btnLogin.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel3.add(btnLogin);
        btnLogin.setBounds(120, 370, 100, 40);

        btnReset.setBackground(new java.awt.Color(255, 0, 0));
        btnReset.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel3.add(btnReset);
        btnReset.setBounds(240, 370, 90, 40);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel2.setText("Password:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(40, 280, 70, 14);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        jLabel1.setText("Email:");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(40, 230, 50, 20);

        jLabel3.setBackground(new java.awt.Color(255, 153, 51));
        jLabel3.setFont(new java.awt.Font("Wide Latin", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" MANAGER  LOGIN ");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(0, 100, 320, 80);

        jLabel5.setForeground(null);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/manager.gif"))); // NOI18N
        jPanel3.add(jLabel5);
        jLabel5.setBounds(0, -10, 670, 510);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 11, 670, 516));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        login();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        txtPass.requestFocus();
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        login();
    }//GEN-LAST:event_txtPassActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtEmail.setText("");
        txtPass.setText("");
        txtEmail.requestFocus();
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ManagerLogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables
}
